import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<div className='flex w-[80%] backdrop-blur-2xl  justify-around m-auto p-2 border-b-2 border-gray-500'>
					<p>
						<Link href={'/'}>Home</Link>
					</p>
					<p>
						<Link href={'/products'}>Products</Link>
					</p>
					<p>
						<Link href={'/about'}>About</Link>
					</p>
					<p>
						<Link href={'/contact'}>Contact</Link>
					</p>
				</div>
				{children}
			</body>
		</html>
	)
}
